export const moviesList = [
    {
        movieId: 1,
        title: "The Lord of the Rings: The Fellowship of the Ring",
        director: "Peter Jackson",
        year: 2001,
        duration: 178,
        cast: ["Elijah Wood", "Ian McKellen", "Viggo Mortensen"],
        country: "New Zealand",
        isFree: false,
        image: "https://i.pinimg.com/736x/a9/6a/00/a96a002732d97f46655bb7ed7a616db5.jpg"
    },
    {
        movieId: 2,
        title: "El secreto de sus ojos",
        director: "Juan José Campanella",
        year: 2009,
        duration: 129,
        cast: ["Ricardo Darín", "Soledad Villamil", "Guillermo Francella"],
        country: "Argentina",
        isFree: false,
        image: "https://i.pinimg.com/736x/a9/6a/00/a96a002732d97f46655bb7ed7a616db5.jpg"
    },
    {
        movieId: 3,
        title: "Nueve reinas",
        director: "Fabián Bielinsky",
        year: 2000,
        duration: 114,
        cast: ["Ricardo Darín", "Gastón Pauls", "Leticia Brédice"],
        country: "Argentina",
        isFree: true,
        image: "https://i.pinimg.com/736x/a9/6a/00/a96a002732d97f46655bb7ed7a616db5.jpg"
    },
    {
        movieId: 4,
        title: "El clan",
        director: "Pablo Trapero",
        year: 2015,
        duration: 108,
        cast: ["Guillermo Francella", "Peter Lanzani", "Lili Popovich"],
        country: "Argentina",
        isFree: true,
        image: "https://i.pinimg.com/736x/a9/6a/00/a96a002732d97f46655bb7ed7a616db5.jpg"
    },
    {
        movieId: 5,
        title: "Argentina, 1985",
        director: "Santiago Mitre",
        year: 2022,
        duration: 140,
        cast: ["Ricardo Darín", "Peter Lanzani", "Alejandra Flechner"],
        country: "Argentina",
        isFree: false,
        image: "https://i.pinimg.com/736x/a9/6a/00/a96a002732d97f46655bb7ed7a616db5.jpg"
    },

    {
        movieId: 6,
        title: "The Shawshank Redemption",
        director: "Frank Darabont",
        year: 1994,
        duration: 142,
        cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
        country: "USA",
        isFree: false,
        image: "https://i.pinimg.com/736x/a9/6a/00/a96a002732d97f46655bb7ed7a616db5.jpg"
    },
    {
        movieId: 7,
        title: "Inception",
        director: "Christopher Nolan",
        year: 2010,
        duration: 148,
        cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
        country: "USA",
        isFree: false,
        image: "https://i.pinimg.com/736x/a9/6a/00/a96a002732d97f46655bb7ed7a616db5.jpg"
    },
    {
        movieId: 8,
        title: "The Dark Knight",
        director: "Christopher Nolan",
        year: 2008,
        duration: 152,
        cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
        country: "USA",
        isFree: false,
        image: "https://i.pinimg.com/736x/a9/6a/00/a96a002732d97f46655bb7ed7a616db5.jpg"
    },
    {
        movieId: 9,
        title: "Fight Club",
        director: "David Fincher",
        year: 1999,
        duration: 139,
        cast: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"],
        country: "USA",
        isFree: true,
        image: "https://i.pinimg.com/736x/a9/6a/00/a96a002732d97f46655bb7ed7a616db5.jpg"
    },
    {
        movieId: 10,
        title: "Pulp Fiction",
        director: "Quentin Tarantino",
        year: 1994,
        duration: 154,
        cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
        country: "USA",
        isFree: false,
        image: "https://i.pinimg.com/736x/a9/6a/00/a96a002732d97f46655bb7ed7a616db5.jpg"
    },
    {
        movieId: 11,
        title: "Forrest Gump",
        director: "Robert Zemeckis",
        year: 1994,
        duration: 142,
        cast: ["Tom Hanks", "Robin Wright", "Gary Sinise"],
        country: "USA",
        isFree: true,
        image: "https://i.pinimg.com/736x/a9/6a/00/a96a002732d97f46655bb7ed7a616db5.jpg"
    },
    {
        movieId: 12,
        title: "The Matrix",
        director: "The Wachowskis",
        year: 1999,
        duration: 136,
        cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
        country: "USA",
        isFree: false,
        image: "https://i.pinimg.com/736x/a9/6a/00/a96a002732d97f46655bb7ed7a616db5.jpg"
    },
    {
        movieId: 13,
        title: "Interstellar",
        director: "Christopher Nolan",
        year: 2014,
        duration: 169,
        cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
        country: "USA",
        isFree: false,
        image: "https://i.pinimg.com/736x/a9/6a/00/a96a002732d97f46655bb7ed7a616db5.jpg"
    },
    {
        movieId: 14,
        title: "La La Land",
        director: "Damien Chazelle",
        year: 2016,
        duration: 128,
        cast: ["Ryan Gosling", "Emma Stone", "John Legend"],
        country: "USA",
        isFree: true,
        image: "https://i.pinimg.com/736x/a9/6a/00/a96a002732d97f46655bb7ed7a616db5.jpg"
    },
    {
        movieId: 15,
        title: "Gladiator",
        director: "Ridley Scott",
        year: 2000,
        duration: 155,
        cast: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen"],
        country: "USA",
        isFree: false,
        image: "https://i.pinimg.com/736x/a9/6a/00/a96a002732d97f46655bb7ed7a616db5.jpg"
    },

    {
        movieId: 16,
        title: "Harry Potter and the Philosopher's Stone",
        director: "Chris Columbus",
        year: 2001,
        duration: 152,
        cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
        country: "England",
        isFree: false,
        image: "https://i.pinimg.com/736x/a9/6a/00/a96a002732d97f46655bb7ed7a616db5.jpg"
    },
    {
        movieId: 17,
        title: "Monty Python and the Holy Grail",
        director: "Terry Gilliam & Terry Jones",
        year: 1975,
        duration: 91,
        cast: ["Graham Chapman", "John Cleese", "Eric Idle"],
        country: "England",
        isFree: true,
        image: "https://i.pinimg.com/736x/a9/6a/00/a96a002732d97f46655bb7ed7a616db5.jpg"
    },
    {
        movieId: 18,
        title: "Pride and Prejudice",
        director: "Joe Wright",
        year: 2005,
        duration: 129,
        cast: ["Keira Knightley", "Matthew Macfadyen", "Brenda Blethyn"],
        country: "England",
        isFree: false,
        image: "https://i.pinimg.com/736x/a9/6a/00/a96a002732d97f46655bb7ed7a616db5.jpg"
    },

    {
        movieId: 19,
        title: "Howl's Moving Castle",
        director: "Hayao Miyazaki",
        year: 2004,
        duration: 119,
        cast: ["Chieko Baisho", "Takuya Kimura", "Akihiro Miwa"],
        country: "Japan",
        isFree: false,
        image: "https://i.pinimg.com/736x/a9/6a/00/a96a002732d97f46655bb7ed7a616db5.jpg"
    },
    {
        movieId: 20,
        title: "Perfect Blue",
        director: "Satoshi Kon",
        year: 1997,
        duration: 81,
        cast: ["Junko Iwao", "Rica Matsumoto", "Shinpachi Tsuji"],
        country: "Japan",
        isFree: true,
        image: "https://i.pinimg.com/736x/a9/6a/00/a96a002732d97f46655bb7ed7a616db5.jpg"
    },
    {
        movieId: 21,
        title: "Relatos salvajes",
        director: "Damián Szifron",
        year: 2014,
        duration: 122,
        cast: ["Ricardo Darín", "Érica Rivas", "Oscar Martínez"],
        country: "Argentina",
        isFree: false,
        image: "https://i.pinimg.com/736x/a9/6a/00/a96a002732d97f46655bb7ed7a616db5.jpg"
    },
];

export const beers = [
    {
        id: 1,
        beerName: "American",
        beerStyle: "IPA",
        price: 3,
        available: true,
    },
    {
        id: 2,
        beerName: "Argenta",
        beerStyle: "IPA",
        price: 4,
        available: false,
    },
    {
        id: 3,
        beerName: "Irish",
        beerStyle: "Red",
        price: 4,
        available: true,
    },
    {
        id: 4,
        beerName: "Scotish",
        beerStyle: "Red",
        price: 3,
        available: true,
    },
    {
        id: 5,
        beerName: "DeEssoCiTratta",
        beerStyle: "APA",
        price: 3,
        available: true,
    },
    {
        id: 6,
        beerName: "Santa APA",
        beerStyle: "APA",
        price: 3,
        available: true,
    },
    {
        id: 7,
        beerName: "German",
        beerStyle: "Pilsen",
        price: 1,
        available: true,
    },
    {
        id: 8,
        beerName: "London Porter",
        beerStyle: "Porter",
        price: 2,
        available: false,
    },
    {
        id: 9,
        beerName: "Scotish ALE",
        beerStyle: "Red",
        price: 5,
        available: false,
    },
];
